### PR TITLE
House settings

### LINKED ISSUE #173: A user should be able to remove themselves from a house.

### PR DESCRIPTION
**Pull request by natmote**
resolves #173 and #189

Note that this removes the zip code field from house creation -- I believe that's what was intended, but if not, I can ditch that commit.

Also, the house settings page is super ugly. I need someone with frontend experience to pick it up after it's merged and make it prettier.

### CODE REVIEW

**Comment by j3ffml** [comment]
Looks good. The behavior is correct, we just need to deal with some technical debt as explained below.

I'm too lazy to scan migration for it, but do you do something for existing InviteProfiles? I only just discovered and fixed the bug that was not updating the invite key to accepted for users that have joined houses, so unless we handle that with a script, it's possible there will be overlap between invitees and members for some pages/houses. Does your migration cover that, or should we write a fix script?

**Comment by natmote** [comment]
we should write a fix script in the form of a migration. I don't know how to tell whether an invite profile should be updated, so I didn't do anything about that bug.

I'll be back at my computer in a few minutes, and I'll chat with you about what we need to do.

**Comment by j3ffml** [comment]
Sounds good. There is straightforward logic to tell whether the invite profile should be updated, so the fix migration shouldn't be hard to write.

**Comment by natmote** [comment]
closing so I can merge #222 and resubmit

**Pull request closed without merging**
