### PR TITLE
Topic repeating tasks

### LINKED ISSUE #8: Tasks
Allow user to add a task, assign frequency, mark an occurrence as completed, edit it, delete it and view its history. Allow house members to see tasks.

### LINKED ISSUE #204: Anybody should be able to edit/delete tasks
All the people in a house should be able to edit/delete the tasks created by other members.

### PR DESCRIPTION
**Pull request by j3ffml**
Back in again, without the migration (and without rebasing). Added change to resolve #204.

Closes #8, #192, #171, #204

### CODE REVIEW

**Comment by natmote** [comment]
do you know why this can't be merged cleanly?

**Comment by j3ffml** [comment]
I touched some of the same templates that @creisman  did in the last pull request that was merged. I'll update it.

**Comment by natmote** [comment]
I tested the first two commits earlier, and the third looks fine.

**Comment by creisman** [comment]
FYI, this appears unrelated to #192... Do you have the right number?

**Comment by j3ffml** [comment]
No that was supposed to be 191, which I did close

On Sun, Dec 2, 2012 at 9:25 PM, Conor Reisman notifications@github.comwrote:

> FYI, this appears unrelated to #192https://github.com/Full-House-UW/fullhouse/issues/192...
> Do you have the right number?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Full-House-UW/fullhouse/pull/212#issuecomment-10941979.

## 

Jeff L

**Pull request merged**
