### PR TITLE
Split up CSS again.

### PR DESCRIPTION
**Pull request by creisman**
Split the CSS into multiple files and adds a block for adding a CSS file.

### CODE REVIEW

**Comment by j3ffml** [comment]
Can this wait until the auth patch is merged? Part of that change moves the location of the template directory, and it will be an annoyance to remove these templates

**Comment by creisman** [comment]
Yeah, no problem.

**Comment by natmote** [comment]
sorry, I just submitted another pull request without merging yours. I don't understand enough about the changes that you and jeff made to be comfortable merging them.

**Comment by creisman** [comment]
I'll fix and resubmit my request...

**Pull request closed without merging**
