### PR TITLE
Added welcome page prototype and static directory.

### PR DESCRIPTION
**Pull request by creisman**
Added a static directory and a welcome page prototype.

Note: Django is not serving from the static directory yet.

### CODE REVIEW

**Comment by natmote** [comment]
You need to make sure that your pull request can merge cleanly. Make sure that you've merged in upstream changes before you submit a pull request.

You can merge upstream changes, then push to your fork, and this pull request will automatically be updated.

**Comment by natmote** [comment]
nevermind, I manually merged it myself

**Comment by creisman** [comment]
What was the conflict on? No one else was supposed to be touching those
files.

**Comment by creisman** [comment]
And thanks.

**Comment by natmote** [comment]
Other people had edited the list of names and the welcome page, and you didn't merge upstream changes before nuking the welcome page.

**Comment by natmote** [comment]
and no problem

**Pull request merged**
