### PR TITLE
Transitioned all auth templates to our base template.

### PR DESCRIPTION
**Pull request by creisman**
Moved the auth templates to extend base.html instead of registration_base.html. We don't use some of these, but I wasn't sure which we did and which we didn't so I moved them all. I tested as many pages as I could find and they all seemed to work alright.

### CODE REVIEW

**Comment by creisman** [comment]
Shahaf didn't properly merge my last request... We're going to try this again...

**Comment by creisman** [comment]
Wtf...?! I didn't hit merge... I hit reopen...

**Comment by natmote** [comment]
SHAME

**Comment by natmote** [comment]
@jlowdermilk Can you weigh in on whether this is a good idea?

**Pull request merged**
