### PR TITLE
Added success messages. Removed deleted CSS files.

### PR DESCRIPTION
**Pull request by creisman**
Removed CSS imports that were deleted.
Solved TODOs in views.
Added success messages to redirect responses.

### CODE REVIEW

**Comment by creisman** [comment]
Hold on this briefly. I'm going to add one more thing to it.

**Comment by creisman** [comment]
Alright, ready to go.

**Comment by JSiu** [comment]
LGTM. @jlowdermilk or @natmote anything you have to say on this one?

**Comment by natmote** [comment]
it looks plausible -- I'm not at my computer, though, so I can't test.

**Comment by snuriel92** [comment]
I'm looking at this now

**Comment by snuriel92** [comment]
Is there a way to maybe make the message stand out a bit more? (Like maybe bolding it or coloring it or making it in a banner?).
If it's more than 2 minutes of work then I say forget it but I think it might help

**Comment by snuriel92** [comment]
Works! Once I get a reply to my last question, I'll merge. Thanks, Conor!

**Comment by creisman** [comment]
Crap. I accidentally just added another commit. I didn't realize this one was still pending...

**Comment by snuriel92** [comment]
That's ok. We'll let it slide. Ummm what do you think about the formatting of the temporary messages?

**Comment by creisman** [comment]
I bolded it. Do we want green messages and red errors?

**Comment by snuriel92** [comment]
How long would that take? I don't think that would be a grade-changer but if it's easy then sure?

**Comment by creisman** [comment]
And red error messages on forms?

**Comment by JSiu** [comment]
Yes please

**Comment by creisman** [comment]
Like 3 seconds? It's just a CSS class.

**Comment by snuriel92** [comment]
ok, as soon as you make the commit, we'll be good

**Comment by creisman** [comment]
Added a logout message, added uninvite message, turned messages green, errors and form errors red.

**Comment by snuriel92** [comment]
It might just be my git-challenged-ness, but I don't see that commit/those changes?

**Comment by creisman** [comment]
https://github.com/Full-House-UW/fullhouse/pull/277#commits-pushed-3d9aa25

There's the commit being added to the list.

Here's the actual commit.

https://github.com/creisman/fullhouse/commit/3d9aa2527f8240004e4e15cd3fd8952f7e2496dd

**Pull request merged**
