### PR TITLE
Topic repeating tasks

### LINKED ISSUE #191: Users should be able to create and edit periodic tasks
- Task is defined with a frequency
- Tasks define a list of participants
- Completing a task puts an instance of that task in the history as completed by the person who clicked complete
- The next task is automatically assigned to the next participant
- Overdue task instances are put into history as incomplete (can be edited to mark as complete)

### PR DESCRIPTION
**Pull request by j3ffml**
closes #191, #171, #187

### CODE REVIEW

**Comment by bkgomez** [comment]
The python stuff is over my head, but I notice in some of the html files you are using hard coded urls. Is it possible to use the {% url  name %} schema for these or is that not doable since there are parameters?

**Comment by j3ffml** [comment]
I'm sure it's doable, just not dealing with it in this ticket.

**Comment by natmote** [comment]
The complete link in history doesn't seem to work. it seems to always have an id of 1. I'll take care of it later, though.

edit: I misunderstood the id -- I thought it was the id of the task instance, but maybe its' not. either way, it's still not working properly.

**Comment by natmote** [comment]
so, if you already have tasks, the migration breaks things. Basically, it sets a default first_due of 11/29, and completely nerfs the value for due.

I'm going to kill off your migration, and add a migration that renames due to first_due, then I'll migrate everything else. I think the sane thing to do is to preserve old tasks and have them happen once, and be first_due on their original due date.

**Pull request closed without merging**
