### PR TITLE
Topic bugfix

### LINKED ISSUE #82: After creating a house, and adding members and such, user is not redirected to dashboard page.
User is directed to a page saying that they have successfully created a house but not able to continue to dashboard (which I think we should just directly link to it). Also, maybe create first announcement: announcement has been added.
I had to go back to our home page and log-in again in order to go to the dashboard page.

### PR DESCRIPTION
**Pull request by j3ffml**
This closes #82, #85

### CODE REVIEW

**Comment by j3ffml** [comment]
Added commit to fix #94

**Comment by cmoiceanu** [comment]
I know Nat been working hard to make things happen on the deployment 
side so I am only asking , not requesting.
Are we going to take this as a bug and push it to test environment or we 
are done as far as pushing bug fixes?

Thanks,
Cornel

**Comment by natmote** [comment]
We are accepting bug fixes until 6:00 PM Monday. During this time, I will release to the test site, and at 9:00 PM on Monday I will tag a release, as long as there are no outstanding serious issues, and push it out to the live site.

**Comment by natmote** [comment]
This looks good.

**Comment by natmote** [comment]
I've merged this into both `release` and `master` and I've made a release to the QA site.

**Comment by cmoiceanu** [comment]
I'll test this on the QA.
Thanks Nat, Jeff

**Pull request merged**
