### PR TITLE
Add pep8 test, fix pep8 errors

### PR DESCRIPTION
**Pull request by j3ffml**
Running './manage.py test' will now also check all source files
for pep8 compliance. Add pep8 to requirements.txt

### CODE REVIEW

**Comment by natmote** [comment]
what is pep8?

**Comment by j3ffml** [comment]
For those unfamiliar, [pep8](http://www.python.org/dev/peps/pep-0008/) is the python style guide. It's mostly simple stuff like indentation and spacing, intended to make code more readable.
Another reason for adding this is to get everyone in the habit of running './manage.py test' before making commits.

**Comment by natmote** [comment]
so what does this do? enforce the standards when we run the tests?

**Comment by j3ffml** [comment]
It can't enforce them, it just tells you if there is code that doesn't meet standards. So when you run the tests, if you have any code that doesn't pass, it'll print out the filename, line number and error, and the pep8 test will fail. It's up to you to go change it by adding a blank line or correcting indentation. This just makes bad formatting fail the test suite.
The code may be perfectly functional, this will just tell you if your formatting is bad (in which case you should feel bad and correct it)

**Comment by natmote** [comment]
sounds handy. thanks

**Pull request merged**
