### PR TITLE
Add twitter bootstrap js and css and use in base template

### PR DESCRIPTION
**Pull request by j3ffml**
Also changed navbar to a bootstrapy navbar

@snuriel92 : bootstrap docs available at http://twitter.github.com/bootstrap/scaffolding.html. some or all of the bootstrap pieces should be useful beautifying the site. The navbar change is just there as an example; feel free to ignore/overwrite it.

### CODE REVIEW

**Comment by natmote** [comment]
this looks really good, but it does appear to fuck up styling elsewhere (for example, login page). I think we should definitely go in this direction, though.

**Comment by natmote** [comment]
I'm not merging it, though, because it needs a little more polish.

**Comment by j3ffml** [comment]
Yeah, I was not intending to merge this as is, it's here as a starting point for frontend to use, as there are a lot of little changes needed to integrate it correctly. I will let @snuriel92 and the others decide whether to merge this.

**Comment by natmote** [comment]
I strongly support making this happen. I think our site will look a lot better and leave a much better impression on Wayne et. al. if we do this.

**Comment by snuriel92** [comment]
Ya, I like it better, too. I'm looking around now and trying to see how to use it for our site.
Thanks, Jeff!

**Pull request merged**
