### PR TITLE
Fix bug in task_history.html template

### PR DESCRIPTION
**Pull request by j3ffml**
Fixes task complete button in task history page

### CODE REVIEW

**Comment by natmote** [comment]
looks plausible. could someone at a computer try it out?

**Comment by snuriel92** [comment]
checking it now

**Comment by creisman** [comment]
It works.

**Comment by snuriel92** [comment]
@creisman  @jlowdermilk  Do we want it to redirect back to the dashboard though? Or do we not care...

**Comment by creisman** [comment]
Yeah, I noticed that. I think it should probably stay on the same page when you complete a task, if that's possible.

**Comment by j3ffml** [comment]
Oh I forgot to do that. You can pass the redirect as a GET parameter 'next'

**Comment by creisman** [comment]
Are you going to put in a patch or would you like me to?

**Comment by j3ffml** [comment]
If you would, pls do.

**Comment by creisman** [comment]
Will do.

**Pull request merged**
