### PR TITLE
CSS fixes

### PR DESCRIPTION
**Pull request by JSiu**

### CODE REVIEW

**Comment by natmote** [comment]
I'll be able to take a look at this at 3

**Comment by JSiu** [comment]
It's pretty minor stuff; changed a dumb mistake, fixed a typo (which, at least on my machine, fixes the alignment problem on the dashboard), and changed some tabs to spaces because the tabs were making the code look dumb in my text editor.

**Comment by natmote** [comment]
thanks. I'll make a release and merge this back into master this afternoon.

**Comment by natmote** [comment]
I've released and merged to master.

**Pull request merged**
