### PR TITLE
Set up announcements and Analytics

### PR DESCRIPTION
**Pull request by creisman**
Added Analytics.

Logout now redirects to /welcome/.

Redirects non-logged in users to a page telling them to make a house instead of the dashboard.

Excluded creator and house from the CreateAnnouncementForm.
Dashboard now renders announcements.
Can create a new announcement at /dashboard/announcement/new/.

### CODE REVIEW

**Comment by creisman** [comment]
Hold up on this for a second. I have a bug I forgot to test.

**Comment by creisman** [comment]
Scratch that. Brandon had a bug. All fixed.

**Comment by j3ffml** [comment]
Edit: disregard this comment, it's good.

Optional: if you wait until #75 is merged, you can have the dashboard redirect users to the actual create_house page.

**Comment by j3ffml** [comment]
LGTM

**Pull request merged**
