### PR TITLE
Improve activation & invite emails

### PR DESCRIPTION
**Pull request by JSiu**

### CODE REVIEW

**Comment by JSiu** [comment]
Testing courtesy of Mr. @creisman

**Comment by snuriel92** [comment]
So Con'rs working on checking this?

**Comment by JSiu** [comment]
Well, he already did. So I just need someone to merge it.

**Comment by creisman** [comment]
Don't merge yet, I have to check her last commit.

**Comment by snuriel92** [comment]
Ok, thanks, both of you.

**Comment by creisman** [comment]
Ugh, there's some stupid whitespace issues (text files don't ignore whitespace like HTML), but it's minor and I'll have to play with it, so I'm going to merge this then fix it locally.

**Pull request merged**
