### PR TITLE
Email-only authentication/registration

### LINKED ISSUE #104: Email authentication
User registration and login using emails only, no usernames

### PR DESCRIPTION
**Pull request by j3ffml**
This closes #104. Everything works (as far as I tested) as before, except now you login with an email, and creation of account requires only email and password.

**IMPORTANT**: this will require a migration of our existing users which can be done in a few ways. The actual migration can be performed simply with a tool provided with by django-email-as-username, but it will refuse to run if there are users with duplicate emails --which our site definitely has. So we have two options to address this:
- We can delete duplicate email users, but we should at least send out an email to each address that has duplicate users to warn them before we do it (easy to write a script to do that).
- (Better option) Django recognizes the '+' trick for multiple emails off of one, e.g. it considers `heff@test.com` and `heff+1@test.com` as separate users, and even though mail sent to either will be directed to `heff@test.com`. So we can have a one-off script which puts a +something on the end of each duplicate email (we could use +username, for example). That way existing duplicate email users will still work but they will have to login with email. We should still send emails to each user to inform them of this change.

Open to suggestions on how to proceed with the migration. We can hold off on merging this until we decide on the approach if we prefer that.

### CODE REVIEW

**Comment by creisman** [comment]
LGTM, but I'll let someone else check again since it's fairly complicated.

**Comment by snuriel92** [comment]
Ya, I don't understand this enough but when a user registers with an email we already have, we shouldn't let them finish the registration and say "This email is already registered with an account". We should still allow example@uw.edu and example+1@uw.edu in case people want to use a "house" for a like a club or event where tasks and announcements would be convenient (and because I have created like 7 accounts for testing....)

**Comment by creisman** [comment]
Do we have any external users or anything that prevents us from ditching the DB and starting over?

**Comment by j3ffml** [comment]
Prod has existing users, so we do need to do a migration. I'm working on a script to do that.

**Comment by natmote** [comment]
I'll take a look at this at some point this evening.

As for the migration, I'd be in favor of the second option, although it may be worth looking to see if we have any existing users in prod with duplicate emails.

If we don't, I'd be okay with just wiping QA and then pushing the changes to prod.

**Comment by j3ffml** [comment]
Update. I have a working script that can do the migration for users in #129. This can be merged, after someone looks at it and agrees on the approach. To test this one, pull it down, delete your local database, and rerun syncdb after the usual update procedure. You should be able to register some users using emails only, and log in with them.

Edit: just noticed your comment @natmote. Have a look at the script in #129; it does the second option. As for users in prod, we have some duplicates that the TA's and Wayne created, so we should do a proper migration.

**Comment by j3ffml** [comment]
Can we merge this yet? I have another change with the view pages for user/house settings that depends on this.

**Comment by natmote** [comment]
I'll take a look at it now.

**Comment by natmote** [comment]
looks good

**Pull request merged**
