### PR TITLE
Topic repeating tasks

### LINKED ISSUE #8: Tasks
Allow user to add a task, assign frequency, mark an occurrence as completed, edit it, delete it and view its history. Allow house members to see tasks.

### LINKED ISSUE #204: Anybody should be able to edit/delete tasks
All the people in a house should be able to edit/delete the tasks created by other members.

### PR DESCRIPTION
**Pull request by j3ffml**
Back in again, without the migration. Added changes to resolve #204.

Closes #8, #192, #171, #204

### CODE REVIEW

**Comment by j3ffml** [comment]
Waiting on migration edits from @natmote before merging this. If other fixes needed, I can add them in before the merge.

**Comment by natmote** [comment]
I'm concerned because these don't appear to be the same commits that you submitted previously. If this is the case, it will make merging hell.

**Comment by natmote** [comment]
did you do a rebase? if so, please undo the rebase and do a merge instead.

**Comment by j3ffml** [comment]
Closing due to rebase unhappiness.

**Pull request closed without merging**
