### PR TITLE
Topic auth (second attempt)

### PR DESCRIPTION
**Pull request by j3ffml**
This change adds user registration and authentication. Uses django-registration module which Cornell added/set up.

Lots of changes, detailed below:
- new app `fullhouse/auth` which is responsible for all auth/registration stuff. includes a custom registration backend so we can create user profiles (one-to-one model with user) with any fields we want (i.e. birthday, hair color, underwear preference)
- templates dir moved to `fullhouse/templates` from `fullhouse/databse/templates`.
- some changes to templates to use django's auth forms and our own registration form.

Still needed:
-  go through all templates in `templates/registration` to make sure they use our base.html template for look/feel.
- update the `FullhouseRegistrationForm` in `fullhouse/auth/forms.py` to have the desired registration fields. the `UserProfile` module in `fullhouse/dashboard/models.py` should be updated accordingly.
- update wiki documentation
- moar pretzels

### CODE REVIEW

**Comment by natmote** [comment]
I still get the error "Error: No module name auth"

I did some digging, and it turns out that there is no `__init__.py` in fullhouse/auth/

I added one, and it seems to be working. Could you add this and push to your branch? The pull request will automatically update.

**Comment by natmote** [comment]
Also, when I try to run a `syncdb`, it complains that the `auth` app does not have a models.py file.

**Comment by j3ffml** [comment]
I see what happened. Somehow auth/**init**.py got deleted, but the compiled **init**.pyc was still there, so I didn't see the problem. I will push the change.

edit: same thing happened with models.

**Comment by j3ffml** [comment]
let me know if it's still failing for you.

**Comment by natmote** [comment]
not sure if you made this change, but the register page only lets me pick a birth year of 2012 or later.

**Comment by j3ffml** [comment]
that was the default, which I didn't change. it's not hard to fix, I just figured I'd let someone else change it (lazy, I know). it should just be changing a parameter in `auth/forms.py`

**Comment by cmoiceanu** [comment]
You guys are great, thank you for doing this.

**Comment by natmote** [comment]
looks good. I'm merging.

**Comment by natmote** [comment]
Also, I'm going to add the command to start a debug smtp server to the documentation

**Comment by j3ffml** [comment]
Thanks! And thanks for checking/testing that.

On Tue, Oct 30, 2012 at 10:12 PM, Nathaniel Mote
notifications@github.comwrote:

> Also, I'm going to add the command to start a debug smtp server to the
> documentation
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Full-House-UW/fullhouse/pull/55#issuecomment-9933113.

## 

Jeff L

**Pull request merged**
