### PR TITLE
Fixed bugs. Updated tests.

### PR DESCRIPTION
**Pull request by creisman**
Fixed bug with add_members redirect after created house.
Fixed bug with message showing when opening house settings.
Fixed incorrect message with create task.

### CODE REVIEW

**Comment by snuriel92** [comment]
Tests still fail on my machine...

# ..FEF...EEE...........

## ERROR: Test create announcement

Traceback (most recent call last):
  File "/home/snuriel/Desktop/fullhouse/fullhouse/test/test_announcements.py", line 16, in setUp
    self.createHouse(self.houseName, self.zipcode)
  File "/home/snuriel/Desktop/fullhouse/fullhouse/test/test_case_base.py", line 97, in createHouse
    [('http://testserver/dashboard/add_members/', 302)]
AssertionError: Lists differ: [('http://testserver/add_membe... != [('http://testserver/dashboard...

First differing element 0:
('http://testserver/add_members/', 302)
('http://testserver/dashboard/add_members/', 302)
- [('http://testserver/add_members/', 302)]
- [('http://testserver/dashboard/add_members/', 302)]
  ?                      ++++++++++

# 

## ERROR: test_crud_task (fullhouse.test.test_tasks.TestTasks)

Traceback (most recent call last):
  File "/home/snuriel/Desktop/fullhouse/fullhouse/test/test_tasks.py", line 21, in setUp
    self.createHouse(self.houseName, self.zipcode)
  File "/home/snuriel/Desktop/fullhouse/fullhouse/test/test_case_base.py", line 97, in createHouse
    [('http://testserver/dashboard/add_members/', 302)]
AssertionError: Lists differ: [('http://testserver/add_membe... != [('http://testserver/dashboard...

First differing element 0:
('http://testserver/add_members/', 302)
('http://testserver/dashboard/add_members/', 302)
- [('http://testserver/add_members/', 302)]
- [('http://testserver/dashboard/add_members/', 302)]
  ?                      ++++++++++

# 

## ERROR: test_history (fullhouse.test.test_tasks.TestTasks)

Traceback (most recent call last):
  File "/home/snuriel/Desktop/fullhouse/fullhouse/test/test_tasks.py", line 21, in setUp
    self.createHouse(self.houseName, self.zipcode)
  File "/home/snuriel/Desktop/fullhouse/fullhouse/test/test_case_base.py", line 97, in createHouse
    [('http://testserver/dashboard/add_members/', 302)]
AssertionError: Lists differ: [('http://testserver/add_membe... != [('http://testserver/dashboard...

First differing element 0:
('http://testserver/add_members/', 302)
('http://testserver/dashboard/add_members/', 302)
- [('http://testserver/add_members/', 302)]
- [('http://testserver/dashboard/add_members/', 302)]
  ?                      ++++++++++

# 

## ERROR: test_update_task (fullhouse.test.test_tasks.TestTasks)

Traceback (most recent call last):
  File "/home/snuriel/Desktop/fullhouse/fullhouse/test/test_tasks.py", line 21, in setUp
    self.createHouse(self.houseName, self.zipcode)
  File "/home/snuriel/Desktop/fullhouse/fullhouse/test/test_case_base.py", line 97, in createHouse
    [('http://testserver/dashboard/add_members/', 302)]
AssertionError: Lists differ: [('http://testserver/add_membe... != [('http://testserver/dashboard...

First differing element 0:
('http://testserver/add_members/', 302)
('http://testserver/dashboard/add_members/', 302)
- [('http://testserver/add_members/', 302)]
- [('http://testserver/dashboard/add_members/', 302)]
  ?                      ++++++++++

# 

## FAIL: test_create_house (fullhouse.test.test_add_house_members.TestAddHouseMembers)

Traceback (most recent call last):
  File "/home/snuriel/Desktop/fullhouse/fullhouse/test/test_add_house_members.py", line 36, in test_create_house
    [('http://testserver/dashboard/add_members/', 302)]
AssertionError: Lists differ: [('http://testserver/add_membe... != [('http://testserver/dashboard...

First differing element 0:
('http://testserver/add_members/', 302)
('http://testserver/dashboard/add_members/', 302)
- [('http://testserver/add_members/', 302)]
- [('http://testserver/dashboard/add_members/', 302)]
  ?                      ++++++++++

# 

## FAIL: Test the user can create a house

Traceback (most recent call last):
  File "/home/snuriel/Desktop/fullhouse/fullhouse/test/test_create_house.py", line 35, in test_create_house
    [('http://testserver/dashboard/add_members/', 302)]
AssertionError: Lists differ: [('http://testserver/add_membe... != [('http://testserver/dashboard...

First differing element 0:
('http://testserver/add_members/', 302)
('http://testserver/dashboard/add_members/', 302)
- [('http://testserver/add_members/', 302)]
- [('http://testserver/dashboard/add_members/', 302)]
  ?                      ++++++++++

---

Ran 22 tests in 7.068s

FAILED (errors=4, failures=2)

**Comment by creisman** [comment]
Are you sure you got pulled changes correctly? That's exactly the same as
before my change.

**Comment by natmote** [comment]
tests pass for me

**Comment by creisman** [comment]
Can anyone else verify?

**Comment by snuriel92** [comment]
hmm maybe I didn't. I'll re-try but meanwhile-- anyone else out there?

**Comment by j3ffml** [comment]
I just pulled it down, and tests pass for me

**Comment by snuriel92** [comment]
ok. works. sorry.

**Pull request merged**
